service: sensors

provider:
  name: aws
  runtime: nodejs8.10
  profile: serverless
  region: eu-west-1
  stage: dev
  memorySize: 256 # default is 1024
  versionFunctions: false
  apiKeys:
    - sensors
  usagePlan:
    quota:
      limit: 500000
      offset: 1
      period: MONTH
    throttle:
      burstLimit: 200
      rateLimit: 10
  environment:
    INFLUX_HOST: ${ssm:influx_host}
    INFLUX_PORT: ${ssm:influx_port}
    INFLUX_USER: ${ssm:influx_user}
    INFLUX_PASSWORD: ${ssm:influx_password}

functions:
  getReadings:
    handler: src/handler.handleGetReadings
    events:
      - http:
          path: sensor
          method: get
          private: false
          cors: true
  postReading:
    handler: src/handler.handlePostReading
    events:
      - http:
          path: sensor
          method: post
          private: true
          cors: true
