name: aa.iot
description: AA.IOT

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 0.1.3
  graphql_flutter: 3.0.1-beta.3
  time_formatter: 1.0.0+5
  charts_flutter: 0.9.0
  shared_preferences: 0.5.6+3
  provider: 4.0.5
  barcode_scan: 2.0.2
  flutter_dotenv: 2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - .env
    - .env.local
    - assets/
