name: plantlab
description: PlantLab

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  barcode_scan: 3.0.1
  charts_flutter: 0.9.0
  cupertino_icons: 0.1.3
  flutter_dotenv: 2.1.0
  flutter_local_notifications: 1.4.3
  graphql_flutter: 3.1.0-beta.6
  provider: 4.1.2
  shared_preferences: 0.5.7
  state_machine: 2.2.0
  time_formatter: 1.0.0+5
  workmanager: 0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - envs/
    - assets/
