apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor-backend
  labels:
    app: sensor-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensor-backend
  template:
    metadata:
      labels:
        app: sensor-backend
    spec:
      containers:
      - name: sensor-backend
        image: gcr.io/the-affordable-project/sensor-backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: NODE_ENV
          value: prod
        - name: NODE_PORT
          value: "8080"
        - name: INFLUX_HOST
          valueFrom:
            secretKeyRef:
              name: influx
              key: host
        - name: INFLUX_PORT
          valueFrom:
            secretKeyRef:
              name: influx
              key: port
        - name: INFLUX_USER
          valueFrom:
            secretKeyRef:
              name: influx
              key: user
        - name: INFLUX_PASSWORD
          valueFrom:
            secretKeyRef:
              name: influx
              key: password
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: databackend
              key: api-key
---

kind: Service
apiVersion: v1
metadata:
  name: sensor-backend
spec:
  selector:
    app: sensor-backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080