name: e2e

on: [push]

jobs:
  e2e:
    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: mkdir -p cypress/screenshots
      - run: mkdir -p cypress/videos
      - run: yarn install --frozen-lockfile
      - run: yarn --cwd client install --frozen-lockfile
      - run: yarn --cwd server install --frozen-lockfile
      - run: yarn --cwd e2e install --frozen-lockfile
      - run: yarn cypress:test
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos
    env:
      CI: true
      NODE_CONFIG: ${{ secrets.NODE_CONFIG }}
